#!/bin/bash

# Copyright 2024 The Convērs Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CURRENT_DIR=$(pwd)
GOPATH_DIR=${GOPATH}

if [ -z "$GOPATH_DIR" ]; then
  echo "GOPATH is not set. Please set it before running this script."
  exit 1
fi

if [[ "$CURRENT_DIR" != *"$GOPATH_DIR"* ]]; then
  echo "Current directory ($CURRENT_DIR) does not contain GOPATH ($GOPATH_DIR)."
  exit 1
fi

CVZPATH=$GOPATH/src/github.com/convrz/convers
CVZPROTOPATH=*.proto
CVZOUT=$GOPATH/src

protoc -I. \
  --proto_path=$CVZPATH \
  -I$CVZPATH/api \
  -I$CVZPATH/third_party/googleapis \
  -I$CVZPATH/third_party/grpc-gateway \
  -I$CVZPATH/third_party/protovalidate/proto/protovalidate \
  --openapiv2_out=$CVZPATH/api/openapi/v1 \
  --grpc-gateway_out=$CVZOUT \
  --go_out=$CVZOUT \
  --go-grpc_out=$CVZOUT \
  --validate_out="lang=go,paths=:$CVZOUT" \
  $CVZPROTOPATH
