// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package news

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type News struct {
	ID       int64
	Content  string
	Category pgtype.Text
}
