#!/bin/bash

# Copyright 2024 The Galxy Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

protoc -I. \
  -Ithird_party/googleapis \
  -Ithird_party/grpc-gateway \
  -Ithird_party/protovalidate/proto/protovalidate \
  --openapiv2_out=pkg \
  --grpc-gateway_out=pkg \
  --grpc-gateway_opt=paths=source_relative \
  --go_out=pkg \
  --go_opt=paths=source_relative \
  --go-grpc_out=pkg \
  --go-grpc_opt=paths=source_relative \
  --validate_out="lang=go,paths=source_relative:pkg" \
  proto/greeter/*.proto
