#!/bin/bash

# Copyright 2024 The Convērs Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CURRENT_DIR=$(pwd)
GOPATH_DIR=${GOPATH}

if [ -z "$GOPATH_DIR" ]; then
  echo "GOPATH is not set. Please set it before running this script."
  exit 1
fi

if [[ "$CURRENT_DIR" != *"$GOPATH_DIR"* ]]; then
  echo "Current directory ($CURRENT_DIR) does not contain GOPATH ($GOPATH_DIR)."
  exit 1
fi

CVZ_PATH=$GOPATH/src/github.com/convrz/convers
PROTO_FILE_PATH=*.proto

protoc -I. \
  --proto_path=$CVZ_PATH \
  -I$CVZ_PATH/third_party/googleapis \
  -I$CVZ_PATH/third_party/grpc-gateway \
  -I$CVZ_PATH/third_party/protovalidate/proto/protovalidate \
  --openapiv2_out=. \
  --grpc-gateway_out=. \
  --grpc-gateway_opt=paths=source_relative \
  --go_out=. \
  --go_opt=paths=source_relative \
  --go-grpc_out=. \
  --go-grpc_opt=paths=source_relative \
  --validate_out="lang=go,paths=source_relative:." \
  $PROTO_FILE_PATH
