name: CI / Test

on:
  # workflow_run:
  #   workflows:
  #     - CI / Lint
  #   types:
  #     - completed
  push:
    branches:
      - main
      - "release/*"
  pull_request:

jobs:
  test:
    name: Run go test and coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: go mod download
        run: |
          go mod download

      - name: go test ./... -cover
        run: |
          go test ./... -cover
